import ClientsOnly from "./components/clientOnly/ClientsOnly";
import Modal from "./components/modals/Modal";
import Model from "./components/modals/Modal";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientsOnly>
          <Modal actionLabel="Submit" title="Hello Man" isOpen />
          <Navbar />
        </ClientsOnly>
        {children}
      </body>
    </html>
  );
}
